### ISSUE TITLE
is there a way to customize GUI ?

### ISSUE THREAD

**Issue by ghost** [TheRole/the_role_management_panel#6]
Is there a way for customize the GUI without change the gem code ?
I think about the header part of this GUI i would like to change for my header blog. 
I know i can directly touch your code inside the gem, but i think it is not the best way, then if i need to update, i will have to do it again.
thank you for this very good gem.

**Comment by the-teacher** [comment]
@jerome2 Hello! Sorry for delay.
API and UI are totally separated. You can customize everything in UI if you need.

there are simple steps to start it:
1. Go to your development folder

``` sh
$ cd ~/rails/projects

$ ls

>> MyRailsApp
```
1. Clone GUI

``` sh
$ git clone git@github.com:TheRole/the_role_management_panel.git

$ ls

>> MyRailsApp
>> the_role_management_panel
```
1. Change your Gemfile  in `MyRailsApp` like this

``` ruby
gem 'the_role_api',              '~> 3.0.0'
gem 'the_role_management_panel', path: '../the_role_management_panel'
```

Change everything in GUI as you wish. Your changes will be applied on each page reloading.
Send your code to your personal github accound and share it for your Applications.

**Comment by ghost** [comment]
ho good, no problem for delay, i have no obligation and the gem is free... so an answer is also not a moral obligation. I'm very happy to use this gem to.

Maybe when i will have a better level i wil do something for be able to add a customized app/views/admin/the_rolemanagment/admin.haml file to be mount if exist instead of this one from gem. And then i will give you the solution i will find for that (i think this could be a simple solution for be able to customize instead... it is an idea).

thanks again.

**Comment by the-teacher** [comment]
@jerome2 :+1:
